### ISSUE TITLE
Download Common Sites

### ISSUE THREAD

**Issue by wyim-pgl** [MBaysanLab/vcf-observer#2]
We are currently testing the VCF-Observer tool at https://bioinformatics.itu.edu.tr/vcf-observer. While most functions are operating smoothly, we encountered an issue with the Venn diagram feature. After generating the diagram, the common sites are displayed, but the chromosome numbers appear as "null."

Could you kindly assist us in resolving this issue? Input and output files has been attached.

Thanks.
Won

```
##fileformat=VCFv4.3

##fileDate=20241003
##source=VCFObserver
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
null_chr	93	.	TA	T	.	PASS	.
null_chr	214	.	A	AC	.	PASS	.
null_chr	457	.	C	CA	.	PASS	.
null_chr	871	.	C	T	.	PASS	.
null_chr	2292	.	G	GC	.	PASS	.
null_chr	6440	.	G	C	.	PASS	.
null_chr	7478	.	A	AT	.	PASS	.
null_chr	7510	.	G	A	.	PASS	.
null_chr	7511	.	G	A	.	PASS	.
null_chr	7721	.	C	CA	.	PASS	.
null_chr	7912	.	GA	G	.
```

[vcfs.zip](https://github.com/user-attachments/files/17251168/vcfs.zip)

**Comment by asimemul** [comment]
I have applied a fix that addresses your issue. Could you check if it is resolved for you as well?

**Comment by asimemul** [comment]
I am closing the issue. Please reopen if unwanted behavior persists.
